-- +migrate Up
CREATE TABLE notification_preferences (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    login_success BOOLEAN NOT NULL DEFAULT TRUE,
    login_failed BOOLEAN NOT NULL DEFAULT TRUE,
    account_locked BOOLEAN NOT NULL DEFAULT TRUE,
    password_changed BOOLEAN NOT NULL DEFAULT TRUE,
    mfa_changes BOOLEAN NOT NULL DEFAULT TRUE,
    api_token_changes BOOLEAN NOT NULL DEFAULT TRUE,
    role_changes BOOLEAN NOT NULL DEFAULT TRUE,
    session_revoked BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
